apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: musicapi
  namespace: music-ns
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musicapi
  targetCPUUtilizationPercentage: 450
